name: CI

on:
  push:
  pull_request:

jobs:
  lint_commits:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_lint_commits.yaml

  release_please:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release_please.yaml
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    secrets:
      GRAPH_FEDERATOR: ${{ secrets.GRAPH_FEDERATOR }}

  helm_lint:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_helm_lint.yaml

  supergraph_generate:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_supergraph_generate.yaml

  supergraph_publish:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - supergraph_generate
    uses: ./.github/workflows/_supergraph_publish.yaml
    permissions:
      contents: read
      packages: write

  actions:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_actions.yaml
    secrets:
      GRAPH_FEDERATOR: ${{ secrets.GRAPH_FEDERATOR }}

  docs:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_docs.yaml
    permissions:
      pages: write
      id-token: write
    with:
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
